sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S5263
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.tsx
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S5263
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.tsx
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S5328
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.tsx
sonar.issue.ignore.multicriteria.e4.ruleKey=javascript:S5328
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.tsx
sonar.issue.ignore.multicriteria.e5.ruleKey=WebStorm:JSXElementNotInternationalized
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.tsx
sonar.issue.ignore.multicriteria.e6.ruleKey=WebStorm:HtmlFormInputWithoutLabel
sonar.issue.ignore.multicriteria.e6.resourceKey=**/*.tsx

# Exclude generated directories from analysis
sonar.exclusions=dist/**/*,build/**/*,Niners/dist/**/*,Niners/build/**/*
